# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish & create release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Publish
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true --self-contained true --verbosity normal

    - name: Create release
      env:
          GITHUB_TOKEN: ${{ secrets.INKSAVER_RELEASE_TOKEN }}
          TAG_NAME: 1.0.${{ github.run_number }}
      run: gh release create $env:TAG_NAME --repo="roddone/InkSaver" --title="roddone/InkSaver $env:TAG_NAME" --generate-notes "${{ github.workspace }}/InkSaver/bin/Release/net9.0/win-x64/publish/*"
